name: urlshortener
services:
  counter:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - microservices
  db:
    image: postgres:alpine
    restart: unless-stopped
    user: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - microservices
  shortener:
    deploy:
      replicas: 3
    build:
      context: .
      dockerfile: shortener.dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SALTSECKEY: ${saltseckey}
    depends_on:
      - counter
      - db
    expose:
      - "8005"
    networks:
      - microservices

volumes:
  postgres_data:
  redis_data:

networks:
  microservices:
    driver: bridge
    name: microservices